version: "3.8"

services:
  redis:
    image: redis:7.4-alpine
    container_name: user_mgmt_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - user_network

  envoy:
    image: envoyproxy/envoy:v1.31-latest
    container_name: user_mgmt_envoy
    ports:
      - "8088:8088"
    volumes:
      - ./etc/docker/envoy/envoy.yaml:/etc/envoy/envoy.yaml

  mongo:
    image: mongo:6.0
    container_name: user_mgmt_mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: knox4life!

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: user_mgmt_mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: knox4life!
      ME_CONFIG_MONGODB_URL: mongodb://root:knox4life!@mongo:27017/

  prometheus:
    container_name: user_mgmt_prometheus
    image: prom/prometheus
    volumes:
      - ./etc/docker/monitoring/prometheus-local.yml:/etc/prometheus/prometheus.yml:Z
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention=20d"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    networks:
      - user_network

  node_exporter:
    container_name: user_mgmt_node_exporter
    image: prom/node-exporter
    ports:
      - "9101:9100"
    networks:
      - user_network

  grafana:
    container_name: user_mgmt_grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - user_network

  jaeger:
    container_name: user_mgmt_jaeger
    restart: always
    image: jaegertracing/all-in-one:1.74.0
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 4317:4317
      - 16686:16686
      - 14268:14268
      - 14250:14250
    networks:
      - user_network

networks:
  user_network:
    driver: bridge
